[workspace]

members = [
  "filecoin-proofs",
  "storage-proofs-core",
  "storage-proofs-porep",
  "storage-proofs-post",
  "fil-proofs-tooling",
  "fil-proofs-param",
  "fr32",
  "sha2raw",
  "filecoin-hashers",
]


[patch.crates-io]
merkletree = { git = "https://github.com/filecoin-project/merkletree", branch = "const-arity" }
neptune = { git = "https://github.com/filecoin-project/neptune", branch = "const-arity" }