[package]
name = "proofs"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]

[dependencies]
sapling-crypto = { git = "https://github.com/zcash-hackworks/sapling-crypto", branch = "master" }
rand = "0.4"
ring = "0.12"
merkle_light = { git = "https://github.com/dignifiedquire/merkle_light", branch = "master" }
openssl = "*"
failure = "0.1"
bellman = "0.1"
byteorder = "1"
lazy_static = "1.0"
memmap = "0.6"
num-bigint = "0.2"
num-traits = "0.2"

[dependencies.pairing]
version = "0.14.2"
features = ["expose-arith"]

[dependencies.blake2-rfc]
git = "https://github.com/gtank/blake2-rfc"
rev = "c7c458429c429b81fea845421f5ab859710fa8af"

[features]
default = ["u128-support"]
u128-support = ["pairing/u128-support"]

[dev-dependencies]
criterion = "0.1.2"
hex-literal = "0.1"
tempfile = "3"

[[bench]]
name = "pedersen"
harness = false
