[package]
name = "fr32"
version = "4.0.2"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
description = "Filecoin proofs Fr/32-byte conversion tooling"
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/filecoin-project/rust-fil-proofs"

[dependencies]
anyhow = "1.0.23"
byte-slice-cast = "1.0.0"
byteorder = "1"
ff = "0.12.0"
thiserror = "1.0.6"
blstrs = "0.5.0"

[dev-dependencies]
bitvec = "0.17"
criterion = "0.3"
itertools = "0.10.3"
# pasta_curves = { git = "https://github.com/zcash/pasta_curves", rev = "2796b6b", features = ["gpu"] }
# halo2_proofs = { git = "https://github.com/drpetervannostrand/halo2", branch = "sha256-chip" }
halo2_proofs = { git = "https://github.com/drpetervannostrand/halo2" }
pretty_assertions = "1.2.0"
rand = "0.8"
rand_xorshift = "0.3"

[[bench]]
name = "fr"
harness = false
