
version: 2
jobs:
  cargo_fetch:
    docker:
      - image: dignifiedquire/rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}
      - run: cargo update
      - run: cargo fetch
      - persist_to_workspace:
          root: "."
          paths:
            - Cargo.lock
      - save_cache:
          key: cargo-v3-{{ checksum "Cargo.toml" }}
          paths:
            - /root/.cargo
            - /root/.rustup
  test:
    docker:
      - image: dignifiedquire/rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}
      - run:
          name: Build and test
          command: cargo +stable test --verbose --frozen
      - run:
          name: Prune the output files
          command: |
            for file in target/debug/* target/debug/.??*; do
              [ -d $file -o ! -x $file ] && rm -r $file
            done
      - persist_to_workspace:
          root: "."
          paths:
            - target/debug/*
  test_release:
    docker:
      - image: dignifiedquire/rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}
      - run:
          name: Build and test in release profile
          command: cargo +stable test --verbose --release --frozen
  test_nightly:
    docker:
      - image: dignifiedquire/rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}
      - run:
          name: Build and test with nightly Rust
          command: cargo +nightly test --verbose --frozen
  rustfmt:
    docker:
      - image: dignifiedquire/rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}
      - run:
          name: Run cargo fmt
          command: cargo fmt -- --check

  clippy:
    docker:
      - image: dignifiedquire/rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: "."
      - restore_cache:
          keys:
            - cargo-v3-{{ checksum "Cargo.toml" }}
      - run:
          name: Run cargo clippy
          command: cargo clippy

workflows:
  version: 2
  test_all:
    jobs:
      - cargo_fetch
      - rustfmt:
          requires:
            - cargo_fetch
      - clippy:
          requires:
            - cargo_fetch
      - test:
          requires:
            - cargo_fetch
      - test_release:
          requires:
            - cargo_fetch
      - test_nightly:
          requires:
            - cargo_fetch
