version: 2.1

jobs:
  cache_linux:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt install nethogs
      - run:
          name: Log network traffic of agent in KB/s. It's the last number of the row.
          background: true
          command: sudo nethogs -t -d 1|grep circleci-machine-agent
      - restore_parameter_cache

  cache_darwin:
    macos:
      xcode: "12.5.0"
    working_directory: ~/crate
    resource_class: large
    steps:
      - checkout
      - run:
          name: Log network traffic of agent
          background: true
          command: nettop -m tcp -t wired -s 1 -d -l 0 -J bytes_in -p circleci-agent
      - restore_parameter_cache

commands:
  restore_parameter_cache:
    steps:
      # Make sure we have different cache for Linux and Darwin.
      - run: uname > os.txt
      - restore_cache:
          name: "Restore parameter cache"
          key: proof-params-v28-k-{{ checksum "os.txt" }}-{{ checksum "filecoin-proofs/parameters.json" }}

workflows:
  version: 2.1
  test_all:
    jobs:
      - cache_linux
      - cache_darwin
