version: 2.1

jobs:
  cache_linux:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt install net-tools nethogs
      - run:
          name: Log number of connections of agent
          background: true
          command: netstat --tcp --programs --continuous|grep circleci-agent
      - run:
          name: Log network traffic of agent in KB/s. It's the last number of the row.
          background: true
          command: sudo nethogs -t -d 1|grep circleci-machine-agent
      - restore_parameter_cache

  cache_darwin:
    macos:
      xcode: "12.5.0"
    working_directory: ~/crate
    resource_class: large
    steps:
      - run: HOMEBREW_NO_AUTO_UPDATE=1 brew install awscli coreutils
      - run:
          name: Increase the maximum concurrent requests for the AWS CLI
          command: aws configure set default.s3.max_concurrent_requests 40
      - checkout
      - run:
          name: Log network traffic of agent and AWS CLI
          background: true
          command: nettop -m tcp -t wired -s 1 -d -l 0 -J bytes_in -p circleci-agent -p Python
      - restore_parameter_cache
      - run:
          name: Download a file from S3 east to verify that about 100Mib/s is possible
          command: timeout 60 aws s3 cp --no-sign-request s3://vmx-temporary-bucket-test/miner_sector_posts.csv miner_sector_posts.csv

commands:
  restore_parameter_cache:
    steps:
      # Make sure we have different cache for Linux and Darwin.
      - run: uname > os.txt
      - restore_cache:
          name: "Restore parameter cache"
          key: proof-params-v28-k-{{ checksum "os.txt" }}-{{ checksum "filecoin-proofs/parameters.json" }}

workflows:
  version: 2.1
  test_all:
    jobs:
      - cache_linux
      - cache_darwin
