[package]
name = "filecoin-proofs"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
sector-base = { path = "../sector-base" }
storage-proofs = { path = "../storage-proofs" }
bitvec = "0.5"
sapling-crypto = { git = "https://github.com/zcash-hackworks/sapling-crypto", branch = "master" }
rand = "0.4"
libc = "0.2"
failure = "0.1"
bellman = "0.1"
lazy_static = "1.0"
memmap = "0.6"
clap = "2"
log = "0.4"
env_logger = "0.5"
colored = "1.6"
pbr = "1.0"
tempfile = "3"

[dev-dependencies]
gperftools = { git = "https://github.com/dignifiedquire/rust-gperftools" }

[dependencies.pairing]
version = "0.14.2"
features = ["expose-arith"]

[build-dependencies]
cbindgen = "0.6.3"

[profile.test]
opt-level = 1

[features]
default = []
profile = []
simd = ["storage-proofs/simd"]
asm = ["storage-proofs/asm"]