[package]
name = "filecoin-proofs"
description = "The Filecoin specific aspects of storage-proofs, including a C based FFI, to generate and verify proofs."
version = "5.2.3"
authors = ["dignifiedquire <dignifiedquire@gmail.com>", "laser <l@s3r.com>", "porcuquine <porcuquine@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/filecoin-project/rust-fil-proofs"
readme = "README.md"

[dependencies]
storage-proofs-core = {git = "https://github.com/filecoin-project/rust-fil-proofs", branch = "dig-refactor-prepare-upgrades" } #{ version = "^5.0.0", path = "../storage-proofs-core" }
storage-proofs-post = { version = "^5.0.0", path = "../storage-proofs-post" }
storage-proofs-porep = { version = "^5.0.0", path = "../storage-proofs-porep" }
fr32 = {git = "https://github.com/filecoin-project/rust-fil-proofs", branch = "dig-refactor-prepare-upgrades" } # { version = "0.1.0", path = "../fr32" }
bitvec = "0.17"
rand = "0.7"
rand_xorshift = "0.2.0"
rand_chacha = "0.2.1"
lazy_static = "1.2"
memmap = "0.7"
byteorder = "1"
itertools = "0.9"
serde = { version = "1.0", features = ["rc", "derive"] }
serde_json = "1.0"
ff = { version = "0.2.3", package = "fff" }
bellperson = "0.9.1"
paired = "0.20.0"
fil-sapling-crypto = "0.6.3"
log = "0.4.7"
rayon = "1.1.0"
blake2s_simd = "0.5.8"
hex = "0.4.0"
merkletree = "0.21.0"
bincode = "1.1.2"
anyhow = "1.0.23"
sha2 = "0.9.1"
typenum = "1.11.2"
bitintr = "0.3.0"
gperftools = { version = "0.2", optional = true }
generic-array = "0.13.2"
groupy = "0.3.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
tempfile = "3"
fil_logger = "0.1.2"

[features]
default = ["gpu"]
cpu-profile = ["gperftools"]
heap-profile = ["gperftools/heap"]
asm = [
  "storage-proofs-core/asm"
]
gpu = [
  "storage-proofs-core/gpu",
  "bellperson/gpu",
  "fil-sapling-crypto/gpu"
]

