[package]
name = "storage-proofs-core"
version = "11.0.2"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
description = "Core parts for proofs of storage"
license = "MIT OR Apache-2.0"
edition = "2018"
repository = "https://github.com/filecoin-project/rust-fil-proofs"
readme = "README.md"

[lib]
bench = false

[dependencies]
filecoin-hashers = { path = "../filecoin-hashers", version = "~6.0.0", default-features = false, features = ["sha256", "poseidon"] }
rand = "0.8"
merkletree = "0.22.0"
byteorder = "1"
config = { version = "0.12.0", default-features = false, features = ["toml"] }
itertools = "0.10.3"
lazy_static = "1.2"
memmap = "0.7"
aes = "0.8.1"
sha2 = "0.10.2"
fs2 = "0.4"
rayon = "1.0.0"
serde = { version = "1.0", features = ["derive"]}
blake2b_simd = "1.0.0"
ff = "0.12.0"
bellperson = "0.22.0"
serde_json = "1.0"
log = "0.4.7"
rand_chacha = "0.3"
generic-array = "0.14.4"
anyhow = "1.0.23"
thiserror = "1.0.6"
cpu-time = { version = "1.0", optional = true }
gperftools = { version = "0.2", optional = true }
num_cpus = "1.10.1"
semver = "1.0.6"
fr32 = { path = "../fr32", version = "~4.0.0"}
blstrs = "0.6.0"
cbc = { version = "0.1.2", features = ["std"] }
halo2_proofs = "0.2.0"
fil-halo2-gadgets = { path = "../fil-halo2-gadgets" }
ec-gpu = "0.2.0"
typemap = "0.3.3"
#neptune = { git = "https://github.com/filecoin-project/neptune", branch = "fr-as-trait-halo2-circuit" }
neptune = { version = "~7.2.0", features = ["bls", "pasta", "arity2", "arity4", "arity8", "arity11", "arity16", "arity24", "arity36"] }
bincode = "1.3.3"

[dev-dependencies]
proptest = "1.0.0"
criterion = "0.3"
rand_xorshift = "0.3.0"
pretty_assertions = "1.2.0"
sha2raw = { path = "../sha2raw", version = "~6.0.0"}
filecoin-hashers = { path = "../filecoin-hashers", version = "~6.0.0", default-features = false, features = ["blake2s", "sha256", "poseidon"] }
tempfile = "3"
blake2s_simd = "1.0.0"
fil_logger = "0.1.6"

[features]
default = ["opencl"]
simd = []
asm = ["sha2/sha2-asm"]
big-sector-sizes-bench = []
measurements = ["cpu-time", "gperftools"]
profile = ["measurements"]

cuda = ["bellperson/cuda", "filecoin-hashers/cuda", "halo2_proofs/cuda"]
opencl = ["bellperson/opencl", "filecoin-hashers/opencl", "halo2_proofs/opencl"]

[[bench]]
name = "sha256"
harness = false

[[bench]]
name = "blake2s"
harness = false

[[bench]]
name = "drgraph"
harness = false

[[bench]]
name = "xor"
harness = false

[[bench]]
name = "merkle"
harness = false

[[bench]]
name = "merkle_groth16_halo2"
harness = false

[[bench]]
name = "misc"
harness = false
