[package]
name = "storage-proofs-post"
version = "12.0.0"
authors = ["dignifiedquire <me@dignifiedquire.com>"]
license = "MIT OR Apache-2.0"
description = "Proofs of Space Time"
edition = "2018"
repository = "https://github.com/filecoin-project/rust-fil-proofs"
readme = "README.md"

[dependencies]
storage-proofs-core = { path = "../storage-proofs-core", version = "~12.0.0", default-features = false}
filecoin-hashers = { path = "../filecoin-hashers", version = "~7.0.0", default-features = false, features = ["poseidon", "sha256"]}
fil_logger = "0.1"
rand = "0.8"
byteorder = "1"
sha2 = "0.10.2"
rayon = "1.0.0"
serde = { version = "1.0", features = ["derive"]}
blake2b_simd = "1.0.0"
ff = "0.12.0"
bellperson = "0.24.0"
log = "0.4.7"
hex = "0.4.0"
generic-array = "0.14.4"
anyhow = "1.0.23"
fr32 = { path = "../fr32", version = "~5.0.0", default-features = false }
blstrs = "0.6.1"
halo2_proofs = { version = "0.2.0", optional = true }
fil-halo2-gadgets = { path = "../fil-halo2-gadgets", optional = true }
nova-snark = { version = "0.17.0", optional = true }
pasta_curves = { version = "0.5.2", optional = true, features = ["repr-c", "serde"], package = "fil_pasta_curves" }

[dev-dependencies]
tempfile = "3"
pretty_assertions = "1.2.0"
filecoin-hashers = { path = "../filecoin-hashers", version = "~7.0.0", default-features = false, features = ["poseidon", "sha256", "blake2s"]}
rand = "0.8"
rand_xorshift = "0.3.0"

[features]
default = ["opencl"]
cuda = ["storage-proofs-core/cuda", "filecoin-hashers/cuda"]
opencl = ["storage-proofs-core/opencl", "filecoin-hashers/opencl"]
nova = ["filecoin-hashers/nova", "storage-proofs-core/nova", "nova-snark", "pasta_curves"]
halo2 = ["filecoin-hashers/halo2", "storage-proofs-core/halo2", "fil-halo2-gadgets", "halo2_proofs"]
big-tests = []
